djangotutorial/urls.py
# coding=utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       url(r'^tutorial/',
                           include('tutorial.urls', namespace="tutorial")),
                       url(r'^admin/', include(admin.site.urls)), )

first/first/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'first.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^nine/square$', 'nine.views.square'),
    url(r'^nine/heroes/$', 'nine.views.heroes'),
    url(r'^nine/heroes/(?P<name>\w{0,50})/$', 'nine.views.heroes'),
)

nine/urls.py
from django.conf.urls import patterns, url

from nine import views

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),
    # url(r'^(?P<question_id>\d+)/square/$', views.square, name='square'),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

tutorial/models.py
from datetime import timedelta

from django.db import models

# Create your models here.
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - timedelta(days=1)

    def __str__(self):
        return self.question_text

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

tutorial/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

tutorial/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from tutorial.models import Question, Choice
from django.contrib import messages


class Index(ListView):
    template_name = 'tutorial/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class Detail(DetailView):
    template_name = 'tutorial/detail.html'
    model = Question


class Results(DetailView):
    template_name = 'tutorial/results.html'
    model = Question


class Vote(View):
    def post(self, request, *args, **kwargs):
        question = get_object_or_404(Question, pk=kwargs['pk'])
        try:
            choice = question.choice_set.get(pk=request.POST.get('choice'))
        except Choice.DoesNotExist:
            messages.add_message(request, messages.ERROR, "Invalid choice")
            return redirect('tutorial:detail', pk=question.id)
        else:
            choice.votes += 1
            choice.save()
            return redirect('tutorial:results', pk=question.id)

templates/tutorial/detail.html
<h1>{{ question.question_text }}</h1>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message
        }}
    </li>
    {% endfor %}
</ul>
{% endif %}
<form action="{% url 'tutorial:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}"
           value="{{ choice.id }}"/>
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text
        }}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>

templates/tutorial/index.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'tutorial:detail' question.id %}">{{
        question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

templates/tutorial/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{
        choice.votes|pluralize }}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'tutorial:detail' question.id %}">Vote again?</a>